### ISSUE TITLE
BestSelllersQuery

### ISSUE THREAD

**Issue by cangokalp** [akaszynski/keepaAPI#11]
Hi, 

BestSellersQuery, won't return anything. 
It says "Best sellers search results not yet available" for valid categories I query

Is this keepa related or python API related

**Comment by akaszynski** [comment]
I think this may be just related to your script, but I can't tell as there's no sample code in your comment.  Here's an API call that retreives category IDs that you can then use for the ``BestSellersQuery``

```python
import keepaAPI
api = keepaAPI.API(mykey)

# get category id numbers for chairs
categories = api.SearchForCategories('chairs')

# print the first 5 catIds
catids = list(categories.keys())
for catid in catids[:5]:
    print(catid, categories[catid]['name'])
```

This is what gets printed:
```
8728936011 Stools, Chairs & Seat Cushions
402283011 Arm Chairs
3259596011 chairs and rockers
5576299011 Desks & Office Chairs
3213923011 chairs and rockers
```

These category ids are what you need to perform a best seller query.  Here, we query for the best sellers of "Arm Chairs"

```python
bestsellers = api.BestSellersQuery('402283011')
```
