### ISSUE TITLE
Discovery of new asin

### ISSUE THREAD

**Issue by awsekfozc** [akaszynski/keepaAPI#17]
Hello, one question puzzled me about how keepa knew the new asin and began to track it. The request is for me. Thank you.

**Comment by akaszynski** [comment]
I’m not sure what you’re referring to.  Could you provide more details?

**Comment by awsekfozc** [comment]
When a new asin is generated, how does keepa discover this asin and start tracking

**Comment by akaszynski** [comment]
I'm not entirely sure actually.  Keepa might crawl similar listings until it finds something new, or it might just be user driven (e.g. user requests to track something and keepa starts tracking it globally)

I maintain the python API for keepa.  You might want to post your question on the keepa discussion forms:
https://keepa.com/#!discuss/
