### ISSUE TITLE
Shipping prices not adding in to 'new' price properly

### ISSUE THREAD

**Issue by chapman3** [akaszynski/keepaAPI#18]
I encountered an asin (B00NPAJ8L4) where the lowest price is not the buy box price. I believe, as a result, I am not getting the shipping of the lowest priced item added in correctly. Elaborating on the asin above:

B00NPAJ8L4, as of time of posting:
- Buy Box: 327.00 + 0 Shipping
- Lowest Price (amazon 3rd party seller): 305 + 15.99 Shipping
- ['data']['NEW'][num_items-1]: 305

I noticed in the notes of the last release the following line: 
"Shipping prices, which previously messed up the data from a product, are now added directly into the price."
This seems to suggest that in cases that lowest isn't buy box that this could occur, but please let me know if it is something I just have missed.

**Comment by volcompt** [comment]
I think that is not an issue with the API but with the database itself. Probably it would be better to report it on the Keepa support forum: https://keepa.com/#!discuss/latest

**Comment by akaszynski** [comment]
Agreed, thanks vollcompt!
