### ISSUE TITLE
Thread error

### ISSUE THREAD

**Issue by volcompt** [akaszynski/keepaAPI#19]
Lately I have been encountering an error when running the API more frequently than I used to. This error seems to be related with the multiple threads part of the API. 

Please see below/attached a screenshot of the error:

![untitled](https://user-images.githubusercontent.com/26249361/37711678-62250ca6-2d09-11e8-89d1-9b5ba38c81dc.png)

I used to get this error every now and then. But now it seems to be more persistent. I have tried to to add the option nthreads=1 but to no avail. I am not sure whether the problem is with my Python installation or with the API itself. I am using Python 3.5.2 :: Anaconda 4.2.0 (64-bit).

I am using the API version keepaAPI-0.12-py3.5. I have tried to update to the newer one, but a similar error occurs with the same frequency and I found the newer API to give less info about the queries (i.e. no output on how many Asins were completed). 

Thanks for the great work on the API Alex.

**Comment by akaszynski** [comment]
I've tested it on Python 2.7 and, more extensively, on Python 3.5.2 (though under Linux).  Sounds like your issue is probably related to my code.

The most recent version uses the standard logging methodology where each module has an individual logger and you control the output by creating an individual stream handler with:

```python
import logging
log = logging.getLogger()
ch = logging.StreamHandler()
ch.setLevel(loglevel.upper())

formatstr = '%(name)-20s - %(levelname)-8s - %(message)s'
ch.setFormatter(logging.Formatter(formatstr))
log.addHandler(ch)
```

Use with the new version if you'd like to track the progress of the request.

In response to the request error.  I just added a new parameter ``allow_errors`` to ``ProductQuery`` that lets you ignore errors if they occur in a thread.  Set ``allow_errors=True`` to allow your query to complete despite errors.  It will mean that your resulting product list will be missing some results, but the request will still complete.

Update to 0.15.1 on PyPi to get the lastest code.  Please let me know if it solves your issue.

**Comment by volcompt** [comment]
Hi Alex, thanks for the reply. 
Quick question: wouldn't it be possible to make a core try again if it gets a thread error instead of skipping a product? Do you have any idea what triggers the error?

**Comment by akaszynski** [comment]
The function has been changed to make 4 more attempts and then report the ASINs it used.

The error might be due to internet connectivity, or a poorly formatted request.  If the issue comes up again we'll be able to narrow it down as ``keepaAPI`` will have a better error message.

**Comment by volcompt** [comment]
Perfect. I will test it today. If anything comes up I will let you know. Thank you very much for the quick turnaround on this issue.

**Comment by volcompt** [comment]
Hi Alex, quick quesiton given that it is the first time I am using this new version of the API. With this new version the code seems to be retrying every 10 seconds to fullfill the request when there are not enough tokens. The previous release would wait 1 minute (or more) before attempting to make the next asin pull. I am not sure if the code is supposed to work like this ... It seems that the previous release had a better way to deal with insufficient tokens. 

![untitled](https://user-images.githubusercontent.com/26249361/37715766-ccf0ab98-2d14-11e8-8813-a36352e70049.png)

Also, if I want to track the progress of the request, where should I add the code you mention above? Right before running api.ProductQuery? 

Sorry for so many questions :)

**Comment by akaszynski** [comment]
Correct, the time delay should be 60 seconds.  Fixed that and uploaded 0.15.2 to PyPi.

I'd add the log code prior to creating the keepaAPI object.  You could also add it before ``api.ProductQuery``

**Comment by volcompt** [comment]
Thanks Alex. 
The line "ch.setLevel(loglevel.upper())" from the logging bit above was throwing an error: "NameError: name 'loglevel' is not defined" . 

I changed the line to: "ch.setLevel(loglevel.upper())" and the code seems to be working (although on the screen output does not show how many ASINs have been completed so far): 

![untitled](https://user-images.githubusercontent.com/26249361/37717143-eb8dcf38-2d17-11e8-8116-02fd9ba18469.png)


But that is fine, I can live with that :)

I am just waiting to get more tokens from Keepa to test a larger pull to see if the original threadrequet issue is solved. I will let you know.

**Comment by akaszynski** [comment]
Fixed the logging bug in ``keepaAPI``.  See the latest version on PyPi.

I also updated my comment above.  It should read:
```python
ch.setLevel('INFO')
```

**Comment by volcompt** [comment]
Thanks for all the help. I have tested it now and it no longer crashes. It retries if error is thrown and after 4 times it just keeps going. I am just not sure if when a 4x thread request error is triggered whether it skips 1 or more Asins if multiple pulls are being requested. Could you clarify that Alex? 

One final thing (which does not bother me) is that the code somehow got my tokens negative. I am not sure why/when this happened as the screen messages seem to imply that the code was waiting when there were not enough tokens available. I will close this issue.
