### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by riverblufftrail** [akaszynski/keepaAPI#2]
Looking to use the keepa api to pull historical prices and sales rank over the last year from amazon.  Any example python code you can point me to that I can lift?

**Comment by akaszynski** [comment]
Hello,

You can get source at:
https://github.com/akaszynski/keepaAPI

or install it using pip with
$ pip install keepaAPI

Cheers!

**Comment by YousefJadallah** [comment]
I tried to use the stats parameter by entering the state time, like below. but there is no effect to the returned object.

products = api.ProductQuery(asin,30)

**Comment by akaszynski** [comment]
If the following doesn't work, please open a new issue on GitHub

import keepaAPI
mykey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
api = keepaAPI.API(mykey)
products = api.ProductQuery(asin,30)
product = products[0]
product['stats']


Yields:
{'stockPerCondition3rdFBA': None, 'buyBoxShipping': -2, 'stockAmazon': -2,
'isAddonItem': None, 'min': [[3468212, 17034], [3508846, 2672], [3514284,
2621], [2835857, 18238], [2532601, 19900], [3688866, 14390], None, None,
None, None, None, [2532601, 1], [2591729, 1], None, [3676544, 1], None,
None, None, None, None, None, None, None, None, None, None, None, None,
None, None, [3410334, 2], None], 'buyBoxPrice': -2, 'buyBoxIsFBA': None,
'buyBoxIsUnqualified': None, 'stockBuyBox': -2, 'buyBoxIsShippable': None,
'maxInInterval': [[3720778, 23900], [3720778, 17996], [3734740, 14010],
[3753028, 981486], [3720778, 23900], [-1, -1], None, None, None, None,
None, [3760210, 5], [3758038, 17], None, [-1, -1], None, None, None, None,
None, None, None, None, None, None, None, None, None, None, None, [3741134,
7025], None], 'buyBoxIsMAP': None, 'max': [[3645608, 23900], [3285100,
21898], [2638951, 79276], [2779405, 1826091], [3609864, 23900], [3676544,
21000], None, None, None, None, None, [3061696, 21], [2956760, 31], None,
[3676544, 1], None, None, None, None, None, None, None, None, None, None,
None, None, None, None, None, [3698330, 7168], None], 'totalOfferCount':
21, 'minInInterval': [[3720778, 23900], [3720778, 17996], [3757828, 8807],
[3754030, 107582], [3720778, 23900], [-1, -1], None, None, None, None,
None, [3720778, 4], [3734092, 12], None, [-1, -1], None, None, None, None,
None, None, None, None, None, None, None, None, None, None, None, [3723492,
2908], None], 'stockPerConditionFBM': None, 'avg90': [23754, 17989, 11461,
572895, 23900, 19265, -1, -1, -1, -1, -1, 5, 18, -1, 0, -1, -1, -1, -1, -1,
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5274, -1], 'tradeInPrice': -2,
'avg180': [22400, 17141, 10077, 832307, 23535, 19265, -1, -1, -1, -1, -1,
6, 19, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
3854, -1], 'retrievedOfferCount': -2, 'outOfStockPercentageInInterval': [0,
0, 0, -1, 0, 100, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1], 'avg30': [23900, 17996,
13456, 745664, 23900, -1, -1, -1, -1, -1, -1, 4, 14, -1, -1, -1, -1, -1,
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5477, -1], 'current':
[23900, 17996, 11003, 947923, 23900, -1, -1, -1, -1, -1, -1, 5, 16, -1, -1,
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 4559, -1],
'buyBoxIsPreorder': None, 'lastOffersUpdate': 3763976, 'buyBoxIsAmazon':
None, 'avg': [23900, 17996, 13456, 745664, 23900, -1, -1, -1, -1, -1, -1,
4, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
5477, -1]}
