### ISSUE TITLE
ProductQuery more tokens spent than asins

### ISSUE THREAD

**Issue by volcompt** [akaszynski/keepaAPI#20]
Hi Alex, 

For the past couple of days I have been puzzeld by the time some pulls take. I realized that whenever I ask the code to pull a large number of asins (usually > 200) it always takes more tokens than the number of asins. The relation is not clear, sometimes it takes more than double, sometimes less than double. 

I can't debug whether the issue comes from the API or there is a problem with the Keepa database. 

Not sure if you have the chance to look into that. 

edit: if you need a Keepa login to test it I can lend you mine.

**Comment by akaszynski** [comment]
Could you try submitting requests individually and see if the same issue occurs?  I'd just setup a loop and submit the requests one by one.

**Comment by volcompt** [comment]
Just done that. It seems to consume 2 tokens per request. Weird?

**Comment by akaszynski** [comment]
Odd.  I'll check that tonight on my end.  It might be double submitting it, but you'd catch that in the log.  They might be charging more for getting history.  Have you tired limiting the request to just the basic info?

**Comment by volcompt** [comment]
Ah, you are probably right. It probably has to do with the fact that their last update was more than 1 hour ago. See the bullet *update* at Keepa. 
https://keepa.com/#!discuss/t/request-products/110

It did not occur so often when I was using Amazon US, but definitely it can happen using other markets. 
My bad for not reading it carefully. 
Thanks Alex.
