### ISSUE TITLE
Pricing for 'New' FBA only items

### ISSUE THREAD

**Issue by tonissimo** [akaszynski/keepaAPI#21]
Get price for FBA sellers only, instead of all items in new condition (FBA+FBM)

**Comment by akaszynski** [comment]
Hello,

Can you please be more specific?  Are you referring to history, or offers?  You should be able to access both using:

```python

import keepaAPI
api = keepaAPI.API(mykey)

products = api.ProductQuery('0134093410', offers=True)

product = products[0]
times = product['data']['NEW_FBA_time']
prices = product['data']['NEW_FBA']

```

Could you please post sample code you've tried?

**Comment by akaszynski** [comment]
I I just tried the code on my end and I think it's sufficient to get the new FBA prices within 90 days.  Be sure to change the ``offer`` parameter to a value between 20 and 100 with the new code.
