### ISSUE TITLE
Offer Parameter Treated Incorrectly (Even After Update)

### ISSUE THREAD

**Issue by lmusolff** [akaszynski/keepaAPI#23]
When querying a list of products and attempting to retrieve offers, e.g. by using 

api.ProductQuery(asins, offers=20, update=0)

the offers parameter is still treated as a bool eventually: while the api.ProductQuery function correctly interprets it as integer, it then passes it on to the (top-level) function ProductQuery via ThreadRequest and the function ProductQuery still checks whether offers is true (which any number above zero gets converted to) and then sets the `offers' parameter for the payload at 1000.

(Off-Topic: Thank you so much for developing this API, makes my life a hell of a lot easier. Really appreciate it!)

**Comment by akaszynski** [comment]
Good catch!  I've updated the code and pushed it here and on PyPi as [keepaAPI 0.15.6](https://pypi.org/project/keepaAPI/).
