### ISSUE TITLE
Update Parameter Always Passed On As `None'

### ISSUE THREAD

**Issue by lmusolff** [akaszynski/keepaAPI#24]
The function ProductQuery (on line 512 of interface.py) does not correctly handle the "update" parameter: it is always passed on as "None" through the settings dict. The mistake is on line 721 I believe.

**Comment by akaszynski** [comment]
Good catch.   Fixed and uploaded to PyPi as 0.15.7

**Comment by lmusolff** [comment]
Thank you! I think PyPi hasn't updated (https://pypi.org/project/keepaAPI/ shows 0.15.6 for me), but maybe that's just a problem on my end.

**Comment by akaszynski** [comment]
Looks like the problem was on PyPi's server side.  Latest [0.15.8](https://pypi.org/project/keepaAPI/#history) has been uploaded.
