### ISSUE TITLE
amazon price and number of sellers -0.01

### ISSUE THREAD

**Issue by threemonks** [akaszynski/keepaAPI#26]
It appears that in version 0.14.2, some amazon price and number of sellers are returned as -0.01, whereas in later version 0.15.0 or 0.15.8, these values are turned into nan? The value -0.01 actually does mean Amazon is out of stock, the the item is completely out of stock, vs nan usually means missing value. Can these values be preserved as it is? I believe the issue is with the following code inside ParseCSV

```
            if isfloat:  # Convert to float price if applicable
                nanmask = values < 0
                values = values.astype(np.float)/100
                values[nanmask] = np.nan
```

Thanks

**Comment by akaszynski** [comment]
I’ve added a new parameter in the ProductQuery function letting you change the behavior. I prefer to include missing data as NAN as it won’t show up on plots.

See the updated documentation on readthedocs at 
https://keepaapi.readthedocs.io/en/latest/

**Comment by akaszynski** [comment]
It’s committed right now on GitHub and will be out on PyPi later today as 0.15.9

**Comment by threemonks** [comment]
Thanks for your quick update. That works for me.
