### ISSUE TITLE
Pulling Best Sellers

### ISSUE THREAD

**Issue by volcompt** [akaszynski/keepaAPI#3]
Hello! Thanks for the Python code! Extremely useful. 
I have a quick question. I managed successfully to request a product data using the code you provided. I was wondering whether the Python code could as well pull the best sellers (as described in this discussion topic):

https://keepa.com/#!discuss/t/request-best-sellers/1298

Thanks,
volcompt

**Comment by volcompt** [comment]
Hi, I wrote some Python code to pull the bestsellers. Below the code, that might be useful for you.
```

# Other libraries
import requests
import pickle

accesskey = 'XXX' # enter real access key here
domain = 'US'
category = '1055398'
dcodes = ['RESERVED', 'US', 'GB', 'DE', 'FR', 'JP', 'CA', 'CN', 'IT', 'ES', 'IN', 'MX']


settings = {'domain': domain,
            'accesskey': accesskey,
            'category': category,
            }

payload = {'key': settings['accesskey'],
               'domain': dcodes.index(settings['domain']), 
               'category': category}

r = requests.get('https://api.keepa.com/bestsellers/?', params=payload)
response =  r.json()

asinlist = response['bestSellersList']['asinList']
filename = response['bestSellersList']['categoryId']

 Save pickle file
filename = str(filename) + '.pckl'
f = open(filename, 'wb')
pickle.dump(response, f)
f.close()
```

**Comment by akaszynski** [comment]
Thanks for that!

I've updated the code, but haven't pushed the update to github pending a
test.  I'm requesting for a demo access key from keepa.  I'll let you know
when I've pushed the update.

**Comment by akaszynski** [comment]
New code is out.  Thanks for the segment of code!

https://github.com/akaszynski/keepaAPI/releases
