### ISSUE TITLE
how to read the stats object?

### ISSUE THREAD

**Issue by tonissimo** [akaszynski/keepaAPI#31]
Hello,

The 'stats' JSON object come out as printed below and I am not sure how to make sense of it. How could I get the 90-day lowest price or 90-day average price from the data below? Thank you!

{'current': [476, 232, 7989, 5966, 604, -1, -1, 603, -1, -1, 940, 15, 1, -1, -1, 17, 45, 317, 476, 8087, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'avg': [494, 232, 7771, 13718, 628, -1, -1, 606, -1, 228, 939, 16, 1, -1, -1, -1, 45, 311, 477, 7459, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'avg30': [476, 232, 7989, 10641, 604, -1, -1, 609, -1, -1, 939, 15, 1, -1, -1, -1, 45, 313, 476, 8087, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'avg90': [494, 232, 7771, 13721, 628, -1, -1, 606, -1, 228, 939, 16, 1, -1, -1, -1, 45, 311, 477, 7459, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'avg180': [477, 232, 7880, 13910, 568, -1, -1, 594, -1, 228, 735, 17, 1, -1, -1, -1, 45, 307, 465, 7660, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'atIntervalStart': [381, 232, 7989, 20782, 493, -1, -1, 595, -1, -1, -1, 17, 1, -1, -1, 18, 45, 310, 381, 8087, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'min': [[2245860, 297], [1360680, 82], [3574296, 205], [3130848, 294], [3213538, 297], None, None, [3814028, 441], None, [3527188, 217], [3907932, 400], [3578960, 8], [2944384, 1], None, None, None, [3186826, 45], [3186826, 166], [3227960, 297], [3527188, 217], None, [3227960, 49766], None, None, None, None, None, None, None, None, None, None], 'max': [[4092488, 993], [3540668, 674], [2998914, 94063], [3552686, 37426], [4090582, 993], None, None, [3541902, 788], None, [4083480, 229], [3522240, 1204], [2857422, 30], [4080544, 3], None, None, None, [3224412, 46], [4170676, 317], [4093832, 993], [3647764, 8097], None, [3239770, 58223], None, None, None, None, None, None, None, None, None, None], 'minInInterval': [[4043282, 381], [4043282, 232], [4080544, 216], [4172384, 5415], [4043282, 493], None, None, [4043282, 595], None, [4083480, 229], [4135266, 940], [4102254, 14], [4043282, 1], None, None, None, [4043282, 45], [4116050, 307], [4043282, 381], [4083480, 229], None, [-1, -1], None, None, None, None, None, None, None, None, None, None], 'maxInInterval': [[4092488, 993], [4109716, 427], [4043282, 7989], [4110024, 28882], [4090582, 993], None, None, [4140580, 633], None, [4083480, 229], [4135266, 940], [4049780, 19], [4080544, 3], None, None, None, [4043282, 45], [4170676, 317], [4093832, 993], [4043282, 8087], None, [-1, -1], None, None, None, None, None, None, None, None, None, None], 'outOfStockPercentageInInterval': [0, 0, 0, -1, 0, -1, -1, 0, -1, 93, 71, -1, -1, -1, -1, -1, -1, -1, 8, 0, -1, 100, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'outOfStockPercentage90': [0, 0, 0, -1, 0, -1, -1, 0, -1, 93, 71, -1, -1, -1, -1, -1, -1, -1, 8, 0, -1, 100, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'outOfStockPercentage30': [0, 0, 0, -1, 0, -1, -1, 0, -1, 100, 13, -1, -1, -1, -1, -1, -1, -1, 0, 0, -1, 100, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], 'stockPerCondition3rdFBA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'stockPerConditionFBM': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'stockAmazon': -2, 'stockBuyBox': -2, 'retrievedOfferCount': -2, 'totalOfferCount': 16, 'tradeInPrice': -1, 'buyBoxPrice': 476, 'buyBoxShipping': 0, 'lastOffersUpdate': 4172642, 'buyBoxIsUnqualified': False, 'buyBoxIsShippable': True, 'buyBoxIsPreorder': False, 'buyBoxIsFBA': True, 'buyBoxIsAmazon': True, 'buyBoxIsMAP': False, 'buyBoxIsUsed': False, 'isAddonItem': False, 'lightningDealInfo': None, 'sellerIdsLowestFBA': None, 'sellerIdsLowestFBM': ['A2FVWI1N0THHUF'], 'offerCountFBA': 0, 'offerCountFBM': 15}

**Comment by keepacom** [comment]
The statistics object is explained here:
https://discuss.keepa.com/t/statistics-object/1308

**Comment by akaszynski** [comment]
Thanks keepa.  I’m going to close this, but it’s a reminder that maybe I need to include more documentation, or at least links to your documentation.
