### ISSUE TITLE
stock parameter to ProductQuery

### ISSUE THREAD

**Issue by threemonks** [akaszynski/keepaAPI#32]
It seems that Keepa ProductQuery takes stock parameter to update the stock quantity. Can you include this parameter in the interface as well? I don't see it now.

https://keepa.com/#!discuss/t/request-products/110

Thanks

**Comment by akaszynski** [comment]
Added 0.15.10 and live on PyPI.  See the updated docs at [readthedocs](https://keepaapi.readthedocs.io/en/latest/product_query.html#keepaAPI.API.ProductQuery).
