### ISSUE TITLE
Subsetting Data Query By Date

### ISSUE THREAD

**Issue by ThomasPepperz** [akaszynski/keepaAPI#33]
Alex, I’ve read through your incredibly helpful documentation and have enjoyed working with the module you’ve put together, but I’ve had a lot of difficulty trying to limit the the price data to only the most recent 180 days. Is there anyway you could tell me or show how I would go about implementing that condition onto a product query so when I submit a query for asin(s) it’s only returning the last 180 days? Not the most recent 180 listings but the earliest (first) price listing for each day of a product for the last 180 days. I’d like return 180 records for each  product, one price per day. Do I use the LISTPRICE key and could I combine that query with one sales rank per day as well? 

It may be just my primary language and experience is with R but I was hoping you would shed some light on the matter as there is very little online information/guidance on Keepa.

**Comment by akaszynski** [comment]
Hello @ThomasPepperz,

I process recent price history from keepa as well and need to reformat the data such that it has one entry for each day.  Multiple entries for a single hour and one for a period of weeks isn't helpful for me either, but it's important to note that this is the way the data is stored at keepa.  It's an efficient method of storage as the price or sales rank is only stored when there is a change, thereby eliminating duplicate entries.

You won't be able to isolate the product query history to the last 180 days, but you can just trim the data after the query.  As for getting a price per day, here's how I do it:

```python
import numpy as np
import pytest
import os
import keepaAPI
import datetime

FAKEKEY = '8ueigrvvnsp5too0atlb5f11veinerkud47p686ekr7vgr9qtj1t1tle15fffkkm'

PRODUCT_ASIN = '0439064872' # yes, it's harry potter
api = keepaAPI.API(FAKEKEY)
request = api.ProductQuery(PRODUCT_ASIN, history=True)

# product data
values = request[0]['data']['USED']
timedates = request[0]['data']['USED_time']

import datetime
from dateutil import rrule
import pandas as pd

# list of days from now to 180 days in the past
ndays = 180
past = datetime.datetime.today() - datetime.timedelta(days=180)
past = past.replace(hour=0, minute=0, second=0, microsecond=0)
target_days = list(rrule.rrule(rrule.DAILY, count=ndays, dtstart=past))

# convert original datetimes to dates and make it unique
dates = [value.replace(hour=0, minute=0) for value in timedates]
dates, idx = np.unique(dates, return_index=True)
valuesbydate = values[idx]

# get the value of the product with one entry per target day
date_values = np.empty(len(target_days))
date_values[:] = np.nan
mask_a = np.isin(dates, target_days)
mask_b = np.isin(target_days, dates)
date_values[mask_b] = valuesbydate[mask_a]

# fill the na values using pandas
# you could do this manually with a loop that carries the values
# forward when "NAN" is encountered
ts = pd.Series(date_values, target_days)
ts = ts.fillna(method='ffill')

filled_values = ts.values  # <-- what you're looking for
target_days  # < associated dates
```

The code isn't pretty or fast, but it works.

**Comment by akaszynski** [comment]
Understandable, it's not a super popular module and most people are just using the web-interface to get their price research done.  It's a powerful tool, and maybe I'll add more examples online.

I'm not exactly getting paid for this work, so sometimes it's tough to find time to add to the docs.  Let me know if you come up with a solution that works for you and maybe I can add it to the documentation or wiki.

**Comment by ThomasPepperz** [comment]
Alex,

If you don't have a cryptocurrency account, you can make one here: https://www.coinbase.com/join/57e1bb4357e9cd0082793ae9

Whenever you get the chance, send me your Ethereum address or post it on here: thomaspepperz@icloud.com and I'll send you a tip for all your trouble. I appreciate your documentation you've produced as well as your response to my issue.

**Comment by akaszynski** [comment]
In response to your second question, I'd store the prices and dates as entries in a dictionary:
```python
products = {}
products['1111111111'] = [dates, values]
products['2222222222'] = [dates2, values2]
```

Each product will have a unique entry and can be rapidly accessed.

As for the coinbase invitation, while I appreciate the gesture, I simply don't have enough time right now to devote to cryptocurrency.  Maybe sometime in the future...

Regardless, I wish you luck with learning Python.  It's a flexible language with lots of libraries and it's probably going to stick around for a while, so it's worth investing some time in.

If you need any additional suggestions or hints, let me know at akascap@gmail.com

**Comment by nakazas** [comment]
Hello, 

When I followed the code provided above, keepaAPI apparently does not exist. 

`>>> import keepaAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'keepaAPI'`

Is there anyway to solve this problem? 

Best regards,
nakazas
