### ISSUE TITLE
Error with keepaAPI

### ISSUE THREAD

**Issue by Kester10** [akaszynski/keepaAPI#4]
Hi, 
After I run this in python 3.5.2. There is an error comes out. 
How could I solve this?
```
from keepaAPI import Interface
accesskey = 'XXXXXXXXXXXXXXXX' # enter real access key here
api = Interface.API(accesskey)

#Single ASIN query
products = api.ProductQuery('059035342X') # returns list of product
```
ERROR:

> INFO   : Connecting to keepa using key XXXXXXXXXXXXXXXX
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     api = Interface.API(accesskey)
>   File "D:\Program Files\Python\lib\site-packages\keepaapi-0.12-py3.5.egg\keepaAPI\Interface.py", line 348, in __init__
>     self.user = UserStatus(self.accesskey)
>   File "D:\Program Files\Python\lib\site-packages\keepaapi-0.12-py3.5.egg\keepaAPI\Interface.py", line 102, in __init__
>     self.UpdateFromServer()
>   File "D:\Program Files\Python\lib\site-packages\keepaapi-0.12-py3.5.egg\keepaAPI\Interface.py", line 107, in UpdateFromServer
>     self.status = GetUserStatus(self.accesskey)
>   File "D:\Program Files\Python\lib\site-packages\keepaapi-0.12-py3.5.egg\keepaAPI\Interface.py", line 91, in GetUserStatus
>     raise Exception(scodes[str(status_code)])
> Exception: REQUEST_REJECTED

**Comment by akaszynski** [comment]
Curious, do you have a proper access key from keepa?  You can get one from:
https://keepa.com/#!api

Alex
