### ISSUE TITLE
Module 'keepaAPI' has no 'API' member

### ISSUE THREAD

**Issue by shawgeek** [akaszynski/keepaAPI#5]
Hello,
I've tried executing the brief example. I've tried it on two different machines, 3 different IDEs, with Python 32bit, Anaconda 32bit and 64bit and I always get the same error:
Module 'keepaAPI' has no 'API' member

Any advice?

Thanks!

**Comment by akaszynski** [comment]
Seems that there were some issues with Python 3 and I've fixed those bugs.
Let me know if that fixes it on you end.

**Comment by nezza** [comment]
Same issue occurs in Python 2 for me:
`>>> import keepaAPI
>>> dir(keepaAPI)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__']`

**Comment by akaszynski** [comment]
The changes weren't uploaded to PyPi.  I've just uploaded it.  See link below.

https://pypi.python.org/pypi/keepaAPI/0.13.3
