### ISSUE TITLE
Stats - Csv

### ISSUE THREAD

**Issue by cangokalp** [akaszynski/keepaAPI#7]
Hi again, 
thanks for the previous fixes. I noticed couple other things, and I was wondering if they could be fixed as well:

1) I don't think the stats field working properly  ;
for a product the returned avg30 :
'avg30': [18217, 12882, 3548, 39440, 23995, 7027, -1, 16848, -1, -1, -1, 13, 77, -1, 0, -20, 35, 31, 13140, 11494, 7916, 7045, 4016, -1, -1, 7427, -1, -1, -1, -1, 2226],

2) What's in the csv field? I was expecting to see something like what's described here -https://keepa.com/#!discuss/t/product-object/116

Can these be fixed?

Thank you very much for the effort, this python API is extremely useful =)

**Comment by akaszynski** [comment]
Here's a code example.  Be sure you're using > 0.14

```python

import keepaAPI
api = keepaAPI.API(mykey)

# Query product
asins = '1454851368'
products = api.ProductQuery(asins)

# CSV list
csv = products[0]['csv']
```

**Comment by akaszynski** [comment]
I'm going to close this issue soon as the csv field is present.  The stats field is generated server side, so you might want to open an issue here:
https://github.com/keepacom/php_api
